import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'en' | 'it';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>('en');

  // Complete translation dictionary
  const t = (key: string): string => {
    const translations: Record<Language, Record<string, string>> = {
      en: {
        'home': 'Home',
        'experiences': 'Experiences',
        'about': 'About',
        'contact': 'Contact',
        'login': 'Login',
        'admin': 'Admin',
        'create': 'Create',
        'edit': 'Edit',
        'delete': 'Delete',
        'save': 'Save',
        'cancel': 'Cancel',
        'title': 'Title',
        'description': 'Description',
        'content': 'Content',
        'viewMore': 'View More',
        'bookNow': 'Book Now',
        'discover': 'Discover Amazing Experiences',
        'discoverSubtitle': 'Explore our selection of unforgettable adventures',
        'featuredExperiences': 'Featured Experiences',
        'englishTab': 'English',
        'italianTab': 'Italian',
        'basicInfo': 'Basic Information',
        'details': 'Details',
        'publish': 'Publish',
        'draft': 'Save as Draft',
        'manageExperiences': 'Manage Experiences',
        'createExperience': 'Create Experience',
        'editExperience': 'Edit Experience',
        'loading': 'Loading...',
        'noExperiences': 'No experiences available',
        'goToAdmin': 'Go to Admin',
        'experienceNotFound': 'Experience not found',
        'experienceNotFoundDesc': 'The requested experience could not be found',
        'experienceUpdated': 'Experience Updated',
        'experienceUpdatedDesc': 'The experience has been successfully updated',
        'experienceCreated': 'Experience Created',
        'experienceCreatedDesc': 'The experience has been successfully created',
        'experienceDeleted': 'Experience Deleted',
        'experienceDeletedDesc': 'The experience has been successfully deleted',
        'statusUpdated': 'Status Updated',
        'statusUpdatedDesc': 'Experience status has been updated successfully',
        'active': 'Active',
        'inactive': 'Inactive',
        'enable': 'Enable',
        'disable': 'Disable',
        'reviews': 'Reviews',
        'noReviewsYet': 'No reviews yet',
        'leaveAReview': 'Leave a Review',
        'yourName': 'Your Name',
        'rating': 'Rating',
        'yourComment': 'Your Comment',
        'submitReview': 'Submit Review',
        'messageSent': 'Message Sent',
        'messageSentDesc': 'Thank you for your message. We will get back to you soon.',
        'sending': 'Sending...',
        'send': 'Send',
        'contactInfo': 'Contact Information',
        'address': 'Address',
        'phone': 'Phone',
        'email': 'Email',
        'hours': 'Opening Hours',
        'weekdays': 'Monday - Friday',
        'weekend': 'Saturday - Sunday',
        'mapPlaceholder': 'Map will be displayed here',
        'getInTouch': 'Get in Touch',
        'name': 'Name',
        'subject': 'Subject',
        'message': 'Message',
        'aboutUs': 'About Us',
        'aboutIntro': 'Welcome to Suite Numero 5, where luxury meets authentic Italian experiences.',
        'aboutMission': 'Our mission is to provide unforgettable experiences that showcase the best of Italian culture, cuisine, and hospitality.',
        'ourStory': 'Our Story',
        'storyContent1': 'Founded with a passion for sharing the authentic Italian lifestyle.',
        'storyContent2': 'We curate unique experiences that connect travelers with local traditions and culture.',
        'ourValues': 'Our Values',
        'authenticity': 'Authenticity',
        'authenticityDesc': 'We believe in genuine, authentic experiences.',
        'quality': 'Quality',
        'qualityDesc': 'We maintain the highest standards in all our services.',
        'sustainability': 'Sustainability',
        'sustainabilityDesc': 'We respect and protect our environment and communities.',
        'community': 'Community',
        'communityDesc': 'We support and engage with local communities.',
        'ourTeam': 'Our Team',
        'teamDesc': 'Meet the passionate individuals behind Suite Numero 5.',
        'founderCEO': 'Founder & CEO',
        'experienceDirector': 'Experience Director',
        'headGuide': 'Head Guide',
        'username': 'Username',
        'password': 'Password',
        'loginSuccess': 'Login Successful',
        'welcomeBack': 'Welcome back!',
        'loginFailed': 'Login Failed',
        'invalidCredentials': 'Invalid username or password',
        'adminLogin': 'Admin Login',
        'experiencesAvailable': 'experiences available',
      },
      it: {
        'home': 'Home',
        'experiences': 'Esperienze',
        'about': 'Chi Siamo',
        'contact': 'Contatti',
        'login': 'Accedi',
        'admin': 'Admin',
        'create': 'Crea',
        'edit': 'Modifica',
        'delete': 'Elimina',
        'save': 'Salva',
        'cancel': 'Annulla',
        'title': 'Titolo',
        'description': 'Descrizione',
        'content': 'Contenuto',
        'viewMore': 'Vedi di Più',
        'bookNow': 'Prenota Ora',
        'discover': 'Scopri Esperienze Straordinarie',
        'discoverSubtitle': 'Esplora la nostra selezione di avventure',
        'featuredExperiences': 'Esperienze in Evidenza',
        'englishTab': 'Inglese',
        'italianTab': 'Italiano',
        'basicInfo': 'Informazioni di Base',
        'details': 'Dettagli',
        'publish': 'Pubblica',
        'draft': 'Salva come Bozza',
        'manageExperiences': 'Gestisci Esperienze',
        'createExperience': 'Crea Esperienza',
        'editExperience': 'Modifica Esperienza',
        'loading': 'Caricamento...',
        'noExperiences': 'Nessuna esperienza disponibile',
        'goToAdmin': 'Vai ad Admin',
        'experienceNotFound': 'Esperienza non trovata',
        'experienceNotFoundDesc': 'L\'esperienza richiesta non è stata trovata',
        'experienceUpdated': 'Esperienza Aggiornata',
        'experienceUpdatedDesc': 'L\'esperienza è stata aggiornata con successo',
        'experienceCreated': 'Esperienza Creata',
        'experienceCreatedDesc': 'L\'esperienza è stata creata con successo',
        'experienceDeleted': 'Esperienza Eliminata',
        'experienceDeletedDesc': 'L\'esperienza è stata eliminata con successo',
        'statusUpdated': 'Stato Aggiornato',
        'statusUpdatedDesc': 'Lo stato dell\'esperienza è stato aggiornato con successo',
        'active': 'Attiva',
        'inactive': 'Inattiva',
        'enable': 'Attiva',
        'disable': 'Disattiva',
        'reviews': 'Recensioni',
        'noReviewsYet': 'Nessuna recensione disponibile',
        'leaveAReview': 'Lascia una Recensione',
        'yourName': 'Il tuo Nome',
        'rating': 'Valutazione',
        'yourComment': 'Il tuo Commento',
        'submitReview': 'Invia Recensione',
        'messageSent': 'Messaggio Inviato',
        'messageSentDesc': 'Grazie per il tuo messaggio. Ti risponderemo presto.',
        'sending': 'Invio in corso...',
        'send': 'Invia',
        'contactInfo': 'Informazioni di Contatto',
        'address': 'Indirizzo',
        'phone': 'Telefono',
        'email': 'Email',
        'hours': 'Orari di Apertura',
        'weekdays': 'Lunedì - Venerdì',
        'weekend': 'Sabato - Domenica',
        'mapPlaceholder': 'La mappa sarà visualizzata qui',
        'getInTouch': 'Contattaci',
        'name': 'Nome',
        'subject': 'Oggetto',
        'message': 'Messaggio',
        'aboutUs': 'Chi Siamo',
        'aboutIntro': 'Benvenuti a Suite Numero 5, dove il lusso incontra le autentiche esperienze italiane.',
        'aboutMission': 'La nostra missione è offrire esperienze indimenticabili che mostrano il meglio della cultura, della cucina e dell\'ospitalità italiana.',
        'ourStory': 'La Nostra Storia',
        'storyContent1': 'Fondati con la passione di condividere l\'autentico stile di vita italiano.',
        'storyContent2': 'Curiamo esperienze uniche che collegano i viaggiatori con le tradizioni e la cultura locale.',
        'ourValues': 'I Nostri Valori',
        'authenticity': 'Autenticità',
        'authenticityDesc': 'Crediamo in esperienze genuine e autentiche.',
        'quality': 'Qualità',
        'qualityDesc': 'Manteniamo i più alti standard in tutti i nostri servizi.',
        'sustainability': 'Sostenibilità',
        'sustainabilityDesc': 'Rispettiamo e proteggiamo il nostro ambiente e le comunità.',
        'community': 'Comunità',
        'communityDesc': 'Supportiamo e collaboriamo con le comunità locali.',
        'ourTeam': 'Il Nostro Team',
        'teamDesc': 'Incontra le persone appassionate dietro Suite Numero 5.',
        'founderCEO': 'Fondatore e CEO',
        'experienceDirector': 'Direttore Esperienze',
        'headGuide': 'Guida Principale',
        'username': 'Nome Utente',
        'password': 'Password',
        'loginSuccess': 'Accesso Effettuato',
        'welcomeBack': 'Bentornato!',
        'loginFailed': 'Accesso Fallito',
        'invalidCredentials': 'Nome utente o password non validi',
        'adminLogin': 'Accesso Admin',
        'experiencesAvailable': 'esperienze disponibili',
      },
    };

    return translations[language][key] || key;
  };

  const value = { language, setLanguage, t };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}